/** Arduino API 速查数据 */
import type { LibEntry, LibCategory } from './types';

export const arduinoCategories: LibCategory[] = [
  { id: 'digital', label: '数字 I/O', icon: '📌', platform: 'arduino' },
  { id: 'analog', label: '模拟 I/O', icon: '📊', platform: 'arduino' },
  { id: 'serial', label: 'Serial', icon: '📡', platform: 'arduino' },
  { id: 'wire', label: 'Wire (I2C)', icon: '🔗', platform: 'arduino' },
  { id: 'spi-lib', label: 'SPI', icon: '🔄', platform: 'arduino' },
  { id: 'time', label: '时间', icon: '⏱', platform: 'arduino' },
  { id: 'interrupt', label: '中断', icon: '⚡', platform: 'arduino' },
  { id: 'math', label: '数学/工具', icon: '🧮', platform: 'arduino' },
];

export const arduinoEntries: LibEntry[] = [
  // ── 数字 I/O ──
  {
    id: 'arduino-pinmode',
    name: 'pinMode()',
    category: 'digital',
    platform: 'arduino',
    description: '设置引脚为输入或输出模式',
    signature: 'void pinMode(uint8_t pin, uint8_t mode)',
    snippet: `pinMode(LED_BUILTIN, OUTPUT);\npinMode(2, INPUT);\npinMode(3, INPUT_PULLUP);`,
    keywords: ['引脚', '模式', '输入', '输出', 'init', 'setup'],
  },
  {
    id: 'arduino-digitalwrite',
    name: 'digitalWrite()',
    category: 'digital',
    platform: 'arduino',
    description: '设置数字引脚电平（HIGH/LOW）',
    signature: 'void digitalWrite(uint8_t pin, uint8_t val)',
    snippet: `digitalWrite(LED_BUILTIN, HIGH);   // 点亮\ndelay(500);\ndigitalWrite(LED_BUILTIN, LOW);    // 熄灭`,
    keywords: ['写', '高电平', '低电平', 'set', 'reset', 'led'],
  },
  {
    id: 'arduino-digitalread',
    name: 'digitalRead()',
    category: 'digital',
    platform: 'arduino',
    description: '读取数字引脚电平',
    signature: 'int digitalRead(uint8_t pin)',
    snippet: `int val = digitalRead(2);\nif (val == HIGH) {\n  // 按键按下\n}`,
    keywords: ['读', '输入', '按键', 'button', 'read'],
  },
  // ── 模拟 I/O ──
  {
    id: 'arduino-analogread',
    name: 'analogRead()',
    category: 'analog',
    platform: 'arduino',
    description: '读取模拟引脚值（0-1023）',
    signature: 'int analogRead(uint8_t pin)',
    snippet: `int sensorValue = analogRead(A0);\nfloat voltage = sensorValue * (5.0 / 1023.0);`,
    keywords: ['模拟', 'ADC', '读取', '传感器', 'sensor'],
  },
  {
    id: 'arduino-analogwrite',
    name: 'analogWrite()',
    category: 'analog',
    platform: 'arduino',
    description: 'PWM 输出（0-255），仅支持 PWM 引脚',
    signature: 'void analogWrite(uint8_t pin, int val)',
    snippet: `analogWrite(9, 128);  // 50% 占空比\nanalogWrite(9, 0);    // 关闭\nanalogWrite(9, 255);  // 全亮`,
    keywords: ['pwm', '模拟输出', '占空比', 'duty', 'led亮度'],
  },
  // ── Serial ──
  {
    id: 'arduino-serial-begin',
    name: 'Serial.begin()',
    category: 'serial',
    platform: 'arduino',
    description: '初始化串口通信',
    signature: 'void Serial.begin(unsigned long baudrate)',
    snippet: `Serial.begin(9600);\nSerial.begin(115200);`,
    keywords: ['初始化', '波特率', 'baudrate', 'init', 'setup'],
  },
  {
    id: 'arduino-serial-print',
    name: 'Serial.print()',
    category: 'serial',
    platform: 'arduino',
    description: '通过串口打印数据（不换行）',
    signature: 'size_t Serial.print(const String &s) / size_t Serial.print(int n, int base)',
    snippet: `Serial.print("温度: ");\nSerial.print(25.6);\nSerial.print(255, HEX);  // 输出 FF`,
    keywords: ['打印', '输出', 'print', 'log', '显示'],
  },
  {
    id: 'arduino-serial-println',
    name: 'Serial.println()',
    category: 'serial',
    platform: 'arduino',
    description: '通过串口打印数据（自动换行）',
    signature: 'size_t Serial.println(const String &s)',
    snippet: `Serial.println("Hello World!");\nSerial.println(analogRead(A0));`,
    keywords: ['打印', '换行', 'println', 'log', '输出'],
  },
  {
    id: 'arduino-serial-available',
    name: 'Serial.available()',
    category: 'serial',
    platform: 'arduino',
    description: '检查串口缓冲区是否有可读数据',
    signature: 'int Serial.available(void)',
    snippet: `if (Serial.available() > 0) {\n  char c = Serial.read();\n  Serial.print("收到: ");\n  Serial.println(c);\n}`,
    keywords: ['可用', '缓冲', 'buffer', 'ready', 'data'],
  },
  {
    id: 'arduino-serial-read',
    name: 'Serial.read()',
    category: 'serial',
    platform: 'arduino',
    description: '从串口读取一个字节',
    signature: 'int Serial.read(void)',
    snippet: `while (Serial.available() > 0) {\n  int incomingByte = Serial.read();\n  Serial.println(incomingByte, HEX);\n}`,
    keywords: ['读取', 'read', 'byte', '接收'],
  },
  // ── Wire (I2C) ──
  {
    id: 'arduino-wire-begin',
    name: 'Wire.begin()',
    category: 'wire',
    platform: 'arduino',
    description: '初始化 I2C（主机模式无参数，从机模式传地址）',
    signature: 'void Wire.begin() / void Wire.begin(uint8_t address)',
    snippet: `Wire.begin();          // 主机\nWire.begin(0x68);      // 从机（地址 0x68）`,
    keywords: ['初始化', 'i2c', 'init', 'setup', 'master', 'slave'],
  },
  {
    id: 'arduino-wire-begin-transmission',
    name: 'Wire.beginTransmission()',
    category: 'wire',
    platform: 'arduino',
    description: '开始 I2C 传输（指定从机地址）',
    signature: 'void Wire.beginTransmission(uint8_t address)',
    snippet: `Wire.beginTransmission(0x68);\nWire.write(0x00);       // 寄存器地址\nWire.write(0x01);       // 数据\nWire.endTransmission();`,
    keywords: ['开始', '传输', 'begin', 'transmission', 'send'],
  },
  {
    id: 'arduino-wire-write',
    name: 'Wire.write()',
    category: 'wire',
    platform: 'arduino',
    description: '向 I2C 总线写入数据',
    signature: 'size_t Wire.write(uint8_t data)',
    snippet: `Wire.beginTransmission(0x68);\nWire.write(0x6B);  // PWR_MGMT_1 寄存器\nWire.write(0x00);  // 唤醒\nWire.endTransmission();`,
    keywords: ['写', '数据', 'write', 'send'],
  },
  {
    id: 'arduino-wire-request-from',
    name: 'Wire.requestFrom()',
    category: 'wire',
    platform: 'arduino',
    description: '请求从从机读取指定字节数',
    signature: 'uint8_t Wire.requestFrom(uint8_t address, uint8_t quantity)',
    snippet: `Wire.beginTransmission(0x68);\nWire.write(0x3B);  // 起始寄存器\nWire.endTransmission(false);\nWire.requestFrom(0x68, 6);\nwhile (Wire.available()) {\n  byte high = Wire.read();\n  byte low = Wire.read();\n  int16_t val = (high << 8) | low;\n}`,
    keywords: ['请求', '读取', 'request', 'read', 'receive'],
  },
  {
    id: 'arduino-wire-read',
    name: 'Wire.read()',
    category: 'wire',
    platform: 'arduino',
    description: '从 I2C 缓冲区读取一个字节',
    signature: 'int Wire.read(void)',
    snippet: `Wire.requestFrom(0x68, 1);\nif (Wire.available()) {\n  uint8_t val = Wire.read();\n}`,
    keywords: ['读取', 'read', 'byte', 'receive'],
  },
  // ── SPI ──
  {
    id: 'arduino-spi-begin',
    name: 'SPI.begin()',
    category: 'spi-lib',
    platform: 'arduino',
    description: '初始化 SPI 总线',
    signature: 'void SPI.begin()',
    snippet: `#include <SPI.h>\nSPI.begin();`,
    keywords: ['初始化', 'init', 'setup', 'start'],
  },
  {
    id: 'arduino-spi-transfer',
    name: 'SPI.transfer()',
    category: 'spi-lib',
    platform: 'arduino',
    description: 'SPI 传输一个字节（同时收发）',
    signature: 'uint8_t SPI.transfer(uint8_t data)',
    snippet: `digitalWrite(SS, LOW);\nuint8_t response = SPI.transfer(0x42);\ndigitalWrite(SS, HIGH);`,
    keywords: ['传输', '收发', 'transfer', 'send', 'receive', 'full duplex'],
  },
  {
    id: 'arduino-spi-settings',
    name: 'SPI.beginTransaction()',
    category: 'spi-lib',
    platform: 'arduino',
    description: '以指定设置开始 SPI 事务',
    signature: 'void SPI.beginTransaction(SPISettings settings)',
    snippet: `SPISettings mySettings(1000000, MSBFIRST, SPI_MODE0);\nSPI.beginTransaction(mySettings);\ndigitalWrite(SS, LOW);\nuint8_t data = SPI.transfer(0x00);\ndigitalWrite(SS, HIGH);\nSPI.endTransaction();`,
    keywords: ['设置', 'settings', 'clock', 'mode', 'transaction'],
  },
  // ── 时间 ──
  {
    id: 'arduino-delay',
    name: 'delay()',
    category: 'time',
    platform: 'arduino',
    description: '毫秒延时（阻塞）',
    signature: 'void delay(unsigned long ms)',
    snippet: `delay(1000);   // 延时 1 秒\ndelay(100);    // 延时 100ms`,
    keywords: ['延时', '等待', 'ms', '毫秒', 'wait', 'sleep'],
  },
  {
    id: 'arduino-delaymicroseconds',
    name: 'delayMicroseconds()',
    category: 'time',
    platform: 'arduino',
    description: '微秒延时（精确，阻塞）',
    signature: 'void delayMicroseconds(unsigned int us)',
    snippet: `delayMicroseconds(10);   // 延时 10μs\ndelayMicroseconds(1000); // 延时 1ms`,
    keywords: ['延时', '微秒', '精确', 'us', 'microsecond'],
  },
  {
    id: 'arduino-millis',
    name: 'millis()',
    category: 'time',
    platform: 'arduino',
    description: '获取系统启动以来的毫秒数',
    signature: 'unsigned long millis(void)',
    snippet: `unsigned long start = millis();\n// ... 执行操作 ...\nif (millis() - start >= 1000) {\n  // 已过 1 秒\n}`,
    keywords: ['时间', '计时', 'time', 'ms', 'elapsed'],
  },
  {
    id: 'arduino-micros',
    name: 'micros()',
    category: 'time',
    platform: 'arduino',
    description: '获取系统启动以来的微秒数',
    signature: 'unsigned long micros(void)',
    snippet: `unsigned long start = micros();\n// ...\nunsigned long elapsed = micros() - start;`,
    keywords: ['时间', '微秒', 'time', 'us', 'precision'],
  },
  // ── 中断 ──
  {
    id: 'arduino-attachinterrupt',
    name: 'attachInterrupt()',
    category: 'interrupt',
    platform: 'arduino',
    description: '附加外部中断回调',
    signature: 'void attachInterrupt(uint8_t pin, voidFuncPtr handler, uint8_t mode)',
    snippet: `volatile unsigned long lastInterrupt = 0;\n\nvoid buttonISR() {\n  if (millis() - lastInterrupt > 200) {\n    // 处理按键\n    lastInterrupt = millis();\n  }\n}\n\nvoid setup() {\n  pinMode(2, INPUT_PULLUP);\n  attachInterrupt(digitalPinToInterrupt(2), buttonISR, FALLING);\n}`,
    keywords: ['中断', 'ISR', 'handler', 'callback', 'external', '按键'],
  },
  {
    id: 'arduino-detachinterrupt',
    name: 'detachInterrupt()',
    category: 'interrupt',
    platform: 'arduino',
    description: '取消外部中断',
    signature: 'void detachInterrupt(uint8_t pin)',
    snippet: `detachInterrupt(digitalPinToInterrupt(2));`,
    keywords: ['取消', '中断', 'disable', 'remove'],
  },
  // ── 数学/工具 ──
  {
    id: 'arduino-map',
    name: 'map()',
    category: 'math',
    platform: 'arduino',
    description: '将值从一个范围映射到另一个范围',
    signature: 'long map(long x, long in_min, long in_max, long out_min, long out_max)',
    snippet: `int sensorVal = analogRead(A0);        // 0-1023\nint pwmVal = map(sensorVal, 0, 1023, 0, 255);\nanalogWrite(9, pwmVal);`,
    keywords: ['映射', '范围', '比例', 'scale', 'convert', '传感器'],
  },
  {
    id: 'arduino-constrain',
    name: 'constrain()',
    category: 'math',
    platform: 'arduino',
    description: '将值限制在指定范围内',
    signature: 'constrain(x, a, b)',
    snippet: `int safeVal = constrain(analogRead(A0), 100, 900);`,
    keywords: ['限制', '范围', 'clamp', 'limit', 'min', 'max'],
  },
  {
    id: 'arduino-constrain',
    name: 'constrain()',
    category: 'math',
    platform: 'arduino',
    description: '将值限制在 [a, b] 范围内',
    signature: '#define constrain(amt,low,high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))',
    snippet: `int safeVal = constrain(rawValue, 0, 255);`,
    keywords: ['限制', 'clamp', 'bound'],
  },
  {
    id: 'arduino-random',
    name: 'random()',
    category: 'math',
    platform: 'arduino',
    description: '生成伪随机数',
    signature: 'long random(long min, long max) / long random(long max)',
    snippet: `randomSeed(analogRead(A0));  // 初始化种子\nint r = random(10, 100);     // 10-99\nint r2 = random(1000);       // 0-999`,
    keywords: ['随机', 'random', 'seed', '数值'],
  },
];
