/** 51 单片机寄存器速查数据 */
import type { LibEntry, LibCategory } from './types';

export const mcs51Categories: LibCategory[] = [
  { id: 'port', label: 'I/O 端口', icon: '📌', platform: 'mcs51' },
  { id: 'timer-reg', label: '定时器', icon: '⏱', platform: 'mcs51' },
  { id: 'uart-reg', label: '串口', icon: '📡', platform: 'mcs51' },
  { id: 'interrupt-reg', label: '中断', icon: '⚡', platform: 'mcs51' },
  { id: 'psw', label: 'PSW / 特殊', icon: '🔧', platform: 'mcs51' },
];

export const mcs51Entries: LibEntry[] = [
  // ── I/O 端口 ──
  {
    id: 'mcs51-p0',
    name: 'P0 (0x80)',
    category: 'port',
    platform: 'mcs51',
    description: 'P0 端口，开漏输出，外接存储器时为地址/数据总线复用',
    signature: 'sfr P0 = 0x80;  // 位寻址: P0.0 ~ P0.7',
    snippet: `P0 = 0xFE;        // P0.0 = 0, 其余 = 1\nP0_0 = 0;          // 单独控制 P0.0\nunsigned char val = P0;  // 读取全部 8 位`,
    keywords: ['端口0', 'IO', '地址总线', 'data bus', 'open drain'],
  },
  {
    id: 'mcs51-p1',
    name: 'P1 (0x90)',
    category: 'port',
    platform: 'mcs51',
    description: 'P1 端口，准双向 I/O，内部上拉',
    signature: 'sfr P1 = 0x90;  // 位寻址: P1.0 ~ P1.7',
    snippet: `P1 = 0xFF;         // 全部输出高\nP1_0 = 0;           // P1.0 置低\nbit sw = P1_0;      // 读 P1.0 引脚`,
    keywords: ['端口1', 'IO', '准双向', 'quasi-bidirectional'],
  },
  {
    id: 'mcs51-p2',
    name: 'P2 (0xA0)',
    category: 'port',
    platform: 'mcs51',
    description: 'P2 端口，准双向 I/O，外接存储器时为高 8 位地址',
    signature: 'sfr P2 = 0xA0;  // 位寻址: P2.0 ~ P2.7',
    snippet: `P2 = 0x0F;        // 高 4 位低，低 4 位高\nunsigned char key = P2 & 0x0F;  // 读取低 4 位`,
    keywords: ['端口2', 'IO', '地址总线', 'address'],
  },
  {
    id: 'mcs51-p3',
    name: 'P3 (0xB0)',
    category: 'port',
    platform: 'mcs51',
    description: 'P3 端口，准双向 I/O，复用第二功能（RXD/TXD/INT0/INT1/T0/T1/WR/RD）',
    signature: 'sfr P3 = 0xB0;  // 位寻址: P3.0 ~ P3.7',
    snippet: `// P3 第二功能：\n// P3.0 = RXD, P3.1 = TXD\n// P3.2 = INT0, P3.3 = INT1\n// P3.4 = T0, P3.5 = T1\n// P3.6 = WR, P3.7 = RD\n\nP3_2 = 1;  // INT0 输入拉高\nbit btn = P3_2;  // 读按键`,
    keywords: ['端口3', 'RXD', 'TXD', 'INT', '第二功能', 'alternate'],
  },
  // ── 定时器 ──
  {
    id: 'mcs51-tmod',
    name: 'TMOD (0x89)',
    category: 'timer-reg',
    platform: 'mcs51',
    description: '定时器模式寄存器，设置 T0/T1 工作模式（不可位寻址）',
    signature: 'sfr TMOD = 0x89;\n// 高 4 位: T1  |  低 4 位: T0\n// Bit[1:0] M1M0: 00=模式0(13位), 01=模式1(16位), 10=模式2(8位自动重装), 11=模式3\n// Bit2 C/T: 0=定时, 1=计数\n// Bit3 GATE: 门控位',
    snippet: `// T1 模式2(8位自动重装), 用于串口波特率\nTMOD = 0x20;\n\n// T0 模式1(16位定时)\nTMOD = 0x01;\n\n// T0 模式1, T1 模式2\nTMOD = 0x21;`,
    keywords: ['模式', 'mode', '定时器模式', 'gate', 'ct'],
  },
  {
    id: 'mcs51-tcon',
    name: 'TCON (0x88)',
    category: 'timer-reg',
    platform: 'mcs51',
    description: '定时器控制寄存器（可位寻址）：TR0/TR1 启停, TF0/TF1 溢出标志, IT0/IT1/IE0/IE1 中断相关',
    signature: 'sfr TCON = 0x88;\n// TCON.4 = TR0, TCON.6 = TR1  (运行控制)\n// TCON.5 = TF0, TCON.7 = TF1  (溢出标志)\n// TCON.0 = IT0, TCON.2 = IT1  (触发方式)\n// TCON.1 = IE0, TCON.3 = IE1  (中断请求)',
    snippet: `TR0 = 1;        // 启动 T0\nTR1 = 1;        // 启动 T1\n\n// 检测 T0 溢出\nif (TF0) {\n  TF0 = 0;      // 清除溢出标志\n  // 重新装载初值\n  TH0 = 0xFC;\n  TL0 = 0x18;\n}`,
    keywords: ['控制', 'control', 'TR0', 'TR1', 'TF0', '溢出', 'start', 'stop'],
  },
  {
    id: 'mcs51-th0-tl0',
    name: 'TH0/TL0 (0x8C/0x8A)',
    category: 'timer-reg',
    platform: 'mcs51',
    description: 'T0 计数器高/低字节。16 位初值装载（12MHz 晶振下 1ms 定时初值：TH0=0xFC, TL0=0x18）',
    signature: 'sfr TH0 = 0x8C;  // T0 高字节\nsfr TL0 = 0x8A;  // T0 低字节',
    snippet: `// 12MHz 晶振, 1ms 定时 (65536 - 1000 = 0xFC18)\nTH0 = 0xFC;\nTL0 = 0x18;\nTMOD = 0x01;  // 模式1\nTR0 = 1;      // 启动\n\n// 11.0592MHz 晶振, 串口波特率 9600\n// T1 模式2: TH1 = 0xFD\nTH1 = 0xFD;`,
    keywords: ['初值', 'preload', 'reload', '计数器', 'counter'],
  },
  {
    id: 'mcs51-th1-tl1',
    name: 'TH1/TL1 (0x8D/0x8B)',
    category: 'timer-reg',
    platform: 'mcs51',
    description: 'T1 计数器高/低字节。常用于串口波特率发生器（模式2自动重装）',
    signature: 'sfr TH1 = 0x8D;  // T1 高字节\nsfr TL1 = 0x8B;  // T1 低字节',
    snippet: `// 串口波特率 9600, 11.0592MHz\nTH1 = 0xFD;\nTMOD |= 0x20;  // T1 模式2\nTR1 = 1;`,
    keywords: ['波特率', 'baudrate', '自动重装', 'auto reload'],
  },
  // ── 串口 ──
  {
    id: 'mcs51-scon',
    name: 'SCON (0x98)',
    category: 'uart-reg',
    platform: 'mcs51',
    description: '串口控制寄存器，设置串口模式、收发控制',
    signature: 'sfr SCON = 0x98;\n// SCON.7 SM0, SCON.6 SM1 (模式选择)\n// SCON.5 SM2 (多机通信)\n// SCON.4 REN (允许接收)\n// SCON.3 TB8, SCON.2 RB8 (第9位)\n// SCON.1 TI (发送中断标志)\n// SCON.0 RI (接收中断标志)',
    snippet: `// 模式1 (8位UART), 允许接收\nSCON = 0x50;  // 0101 0000\n\n// 等待发送完成\nwhile (!TI);\nTI = 0;\n\n// 检查接收完成\nif (RI) {\n  RI = 0;\n  unsigned char ch = SBUF;\n}`,
    keywords: ['串口控制', '模式', 'SM0', 'SM1', 'REN', 'TI', 'RI'],
  },
  {
    id: 'mcs51-sbuf',
    name: 'SBUF (0x99)',
    category: 'uart-reg',
    platform: 'mcs51',
    description: '串口数据缓冲器。写入=发送，读取=接收（两个物理寄存器共用地址）',
    signature: 'sfr SBUF = 0x99;',
    snippet: `// 发送一个字节\nSBUF = 'A';\nwhile (!TI);\nTI = 0;\n\n// 接收一个字节\nwhile (!RI);\nRI = 0;\nunsigned char data = SBUF;`,
    keywords: ['数据', 'buffer', '收发', 'send', 'receive', 'byte'],
  },
  {
    id: 'mcs51-pcon',
    name: 'PCON (0x87)',
    category: 'uart-reg',
    platform: 'mcs51',
    description: '电源控制寄存器。SMOD 位控制串口波特率加倍',
    signature: 'sfr PCON = 0x87;\n// PCON.7 SMOD: 1=波特率加倍\n// PCON.0 IDLE, PCON.1 PD (省电模式)',
    snippet: `// 串口波特率加倍\nPCON |= 0x80;  // SMOD = 1\n\n// 波特率 9600x2 = 19200, 11.0592MHz\nTH1 = 0xFD;\nPCON |= 0x80;`,
    keywords: ['电源', 'SMOD', '波特率加倍', 'power', 'baudrate'],
  },
  // ── 中断 ──
  {
    id: 'mcs51-ie',
    name: 'IE (0xA8)',
    category: 'interrupt-reg',
    platform: 'mcs51',
    description: '中断允许寄存器。EA=总开关, 各位控制对应中断使能',
    signature: 'sfr IE = 0xA8;\n// IE.7 EA  (总中断使能)\n// IE.6 ET2 (T2 中断, 52系列)\n// IE.5 ES  (串口中断)\n// IE.4 ET1 (T1 中断)\n// IE.3 EX1 (外部中断1)\n// IE.2 ET0 (T0 中断)\n// IE.1 EX0 (外部中断0)',
    snippet: `// 开启总中断 + T0 中断\nEA = 1;\nET0 = 1;\n\n// 开启全部常用中断\nIE = 0x87;  // EA + ET0 + EX0 + ET1\n\n// 关闭所有中断\nEA = 0;`,
    keywords: ['中断', '使能', 'enable', 'EA', '全局', 'interrupt'],
  },
  {
    id: 'mcs51-ip',
    name: 'IP (0xB8)',
    category: 'interrupt-reg',
    platform: 'mcs51',
    description: '中断优先级寄存器。置1=高优先级，清0=低优先级',
    signature: 'sfr IP = 0xB8;\n// IP.7 PT2 (T2)\n// IP.6 PS  (串口)\n// IP.5 PT1 (T1)\n// IP.4 PX1 (外部中断1)\n// IP.3 PT0 (T0)\n// IP.2 PX0 (外部中断0)',
    snippet: `// 串口中断设为高优先级\nPS = 1;\n\n// 外部中断0 高优先级\nPX0 = 1;\n\n// T0 高优先级\nPT0 = 1;`,
    keywords: ['优先级', 'priority', '嵌套', 'nesting'],
  },
  {
    id: 'mcs51-tcon-int',
    name: 'TCON 中断位',
    category: 'interrupt-reg',
    platform: 'mcs51',
    description: 'TCON 中与中断相关的位：IT0/IT1（触发方式）, IE0/IE1（中断请求标志）',
    signature: '// TCON (0x88)\nIT0 = 0/1;  // 0=低电平触发, 1=下降沿触发\nIT1 = 0/1;\nIE0 = 0/1;  // 外部中断0 请求标志（硬件置位，进入中断自动清零）\nIE1 = 0/1;',
    snippet: `// INT0 下降沿触发\nIT0 = 1;\n\n// INT1 低电平触发\nIT1 = 0;`,
    keywords: ['触发', '下降沿', '低电平', 'edge', 'level', 'external'],
  },
  // ── PSW / 特殊寄存器 ──
  {
    id: 'mcs51-psw',
    name: 'PSW (0xD0)',
    category: 'psw',
    platform: 'mcs51',
    description: '程序状态字：进位/辅助进位/溢出/奇偶校验 + 寄存器组选择',
    signature: 'sfr PSW = 0xD0;\n// PSW.7 CY  (进位标志)\n// PSW.6 AC  (辅助进位)\n// PSW.5 F0  (用户标志)\n// PSW.4 RS1 (寄存器组选择高位)\n// PSW.3 RS0 (寄存器组选择低位)\n// PSW.2 OV  (溢出标志)\n// PSW.1 -   (保留)\n// PSW.0 P   (奇偶校验)',
    snippet: `// 检查进位标志\nunsigned char a = 200, b = 100;\nunsigned int sum = a + b;  // 使用 int 防溢出\n\n// 切换到寄存器组1\nRS0 = 1;\nRS1 = 0;\n\n// 检查溢出\nif (OV) {\n  // 运算溢出\n}`,
    keywords: ['状态', 'status', 'carry', 'overflow', 'parity', '寄存器组'],
  },
  {
    id: 'mcs51-sp',
    name: 'SP (0x81)',
    category: 'psw',
    platform: 'mcs51',
    description: '堆栈指针。复位后初始值 0x07，指向内部 RAM',
    signature: 'sfr SP = 0x81;',
    snippet: `// 初始化堆栈到 0x60（避开寄存器组和位寻址区）\nSP = 0x5F;\n\n// 典型初始化（上电后第一条指令）\nMOV SP, #60H`,
    keywords: ['堆栈', 'stack', 'pointer', '栈指针'],
  },
  {
    id: 'mcs51-dptr',
    name: 'DPTR (0x82/0x83)',
    category: 'psw',
    platform: 'mcs51',
    description: '数据指针（16位），由 DPH + DPL 组成，用于访问外部存储器',
    signature: 'sfr DPL = 0x82;  // 低字节\nsfr DPH = 0x83;  // 高字节',
    snippet: `// 汇编：\nMOV DPTR, #1000H\nMOVX A, @DPTR    // 读外部 RAM\nMOVX @DPTR, A    // 写外部 RAM\n\n// C51：\nunsigned char xdata *ptr = (unsigned char xdata *)0x1000;\n*ptr = 0x42;\nunsigned char val = *ptr;`,
    keywords: ['数据指针', 'data pointer', '外部存储', 'xdata', 'DPH', 'DPL'],
  },
  {
    id: 'mcs51-a-b',
    name: 'A (0xE0) / B (0xF0)',
    category: 'psw',
    platform: 'mcs51',
    description: '累加器 A 和寄存器 B，乘除法运算使用 A 和 B 配合',
    signature: 'sfr ACC = 0xE0;  // 累加器 A\nsfr B   = 0xF0;  // 寄存器 B',
    snippet: `// 乘法: A × B → BA (16位结果)\n// MOV A, #10\n// MOV B, #20\n// MUL AB      ; A=200低8位, B=高8位\n\n// 除法: A ÷ B → A(商) B(余数)\n// DIV AB\n\n// C51 编译器会自动使用这些寄存器`,
    keywords: ['累加器', 'accumulator', '乘法', '除法', 'multiply', 'divide'],
  },
  // ── 常用代码模板 ──
  {
    id: 'mcs51-timer0-isr',
    name: 'T0 中断模板',
    category: 'timer-reg',
    platform: 'mcs51',
    description: '定时器0 1ms 中断服务程序模板（11.0592MHz 晶振）',
    signature: 'void timer0_isr() interrupt 1',
    snippet: `#include <reg51.h>\n\nvoid Timer0_Init() {\n  TMOD |= 0x01;   // T0 模式1\n  TH0 = 0xFC;     // 1ms 初值 (11.0592MHz)\n  TL0 = 0x18;\n  ET0 = 1;        // 允许 T0 中断\n  EA = 1;         // 开总中断\n  TR0 = 1;        // 启动 T0\n}\n\nvoid Timer0_ISR() interrupt 1 {\n  TH0 = 0xFC;     // 重新装载\n  TL0 = 0x18;\n  // 你的逻辑\n}`,
    keywords: ['中断模板', 'isr', 'handler', '定时器中断', 'template'],
  },
  {
    id: 'mcs51-uart-init',
    name: '串口初始化模板',
    category: 'uart-reg',
    platform: 'mcs51',
    description: '串口初始化模板：模式1，波特率 9600（11.0592MHz 晶振）',
    signature: 'void UART_Init()',
    snippet: `#include <reg51.h>\n\nvoid UART_Init() {\n  TMOD |= 0x20;   // T1 模式2 (8位自动重装)\n  TH1 = 0xFD;     // 波特率 9600\n  SCON = 0x50;    // 模式1, 允许接收\n  TR1 = 1;        // 启动 T1\n}\n\nvoid UART_Send(char c) {\n  SBUF = c;\n  while (!TI);\n  TI = 0;\n}\n\nchar UART_Recv() {\n  while (!RI);\n  RI = 0;\n  return SBUF;\n}`,
    keywords: ['串口模板', '初始化', 'uart', 'baudrate', 'template'],
  },
];
