/** STM32 HAL 库速查数据 */
import type { LibEntry, LibCategory } from './types';

export const stm32Categories: LibCategory[] = [
  { id: 'gpio', label: 'GPIO', icon: '📌', platform: 'stm32hal' },
  { id: 'uart', label: 'UART', icon: '📡', platform: 'stm32hal' },
  { id: 'spi', label: 'SPI', icon: '🔄', platform: 'stm32hal' },
  { id: 'timer', label: 'Timer', icon: '⏱', platform: 'stm32hal' },
  { id: 'adc', label: 'ADC', icon: '📊', platform: 'stm32hal' },
  { id: 'i2c', label: 'I2C', icon: '🔗', platform: 'stm32hal' },
];

export const stm32Entries: LibEntry[] = [
  // ── GPIO ──
  {
    id: 'stm32-gpio-init',
    name: 'HAL_GPIO_Init',
    category: 'gpio',
    platform: 'stm32hal',
    description: '初始化 GPIO 引脚（模式/上拉/速度）',
    signature: 'void HAL_GPIO_Init(GPIO_TypeDef *GPIOx, GPIO_InitTypeDef *GPIO_Init)',
    snippet: `GPIO_InitTypeDef gpio = {0};\ngpio.Pin = GPIO_PIN_5;\ngpio.Mode = GPIO_MODE_OUTPUT_PP;\ngpio.Pull = GPIO_NOPULL;\ngpio.Speed = GPIO_SPEED_FREQ_LOW;\nHAL_GPIO_Init(GPIOA, &gpio);`,
    keywords: ['初始化', '配置', '引脚', 'init', 'setup'],
  },
  {
    id: 'stm32-gpio-write',
    name: 'HAL_GPIO_WritePin',
    category: 'gpio',
    platform: 'stm32hal',
    description: '设置 GPIO 引脚电平',
    signature: 'void HAL_GPIO_WritePin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)',
    snippet: `HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);\nHAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET);`,
    keywords: ['写', '高电平', '低电平', '置位', '清零', 'write', 'set', 'reset'],
  },
  {
    id: 'stm32-gpio-read',
    name: 'HAL_GPIO_ReadPin',
    category: 'gpio',
    platform: 'stm32hal',
    description: '读取 GPIO 引脚电平',
    signature: 'GPIO_PinState HAL_GPIO_ReadPin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)',
    snippet: `GPIO_PinState state = HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0);\nif (state == GPIO_PIN_SET) {\n  // 高电平\n}`,
    keywords: ['读', '输入', 'read', 'input'],
  },
  {
    id: 'stm32-gpio-toggle',
    name: 'HAL_GPIO_TogglePin',
    category: 'gpio',
    platform: 'stm32hal',
    description: '翻转 GPIO 引脚电平',
    signature: 'void HAL_GPIO_TogglePin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)',
    snippet: `HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);`,
    keywords: ['翻转', 'toggle', 'blink', '闪烁'],
  },
  {
    id: 'stm32-gpio-clk-enable',
    name: '__HAL_RCC_GPIOx_CLK_ENABLE',
    category: 'gpio',
    platform: 'stm32hal',
    description: '使能 GPIO 端口时钟（使用前必须调用）',
    signature: '__HAL_RCC_GPIOx_CLK_ENABLE()',
    snippet: `__HAL_RCC_GPIOA_CLK_ENABLE();\n__HAL_RCC_GPIOB_CLK_ENABLE();\n__HAL_RCC_GPIOC_CLK_ENABLE();`,
    keywords: ['时钟', '使能', 'clock', 'enable', 'rcc'],
  },
  // ── UART ──
  {
    id: 'stm32-uart-init',
    name: 'HAL_UART_Init',
    category: 'uart',
    platform: 'stm32hal',
    description: '初始化 UART 外设',
    signature: 'HAL_StatusTypeDef HAL_UART_Init(UART_HandleTypeDef *huart)',
    snippet: `UART_HandleTypeDef huart1 = {0};\nhuart1.Instance = USART1;\nhuart1.Init.BaudRate = 115200;\nhuart1.Init.WordLength = UART_WORDLENGTH_8B;\nhuart1.Init.StopBits = UART_STOPBITS_1;\nhuart1.Init.Parity = UART_PARITY_NONE;\nhuart1.Init.Mode = UART_MODE_TX_RX;\nHAL_UART_Init(&huart1);`,
    keywords: ['串口', '初始化', '波特率', 'baudrate', 'serial'],
  },
  {
    id: 'stm32-uart-transmit',
    name: 'HAL_UART_Transmit',
    category: 'uart',
    platform: 'stm32hal',
    description: '通过 UART 发送数据（阻塞）',
    signature: 'HAL_StatusTypeDef HAL_UART_Transmit(UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t msg[] = "Hello\\r\\n";\nHAL_UART_Transmit(&huart1, msg, sizeof(msg) - 1, 1000);`,
    keywords: ['发送', '输出', 'tx', 'transmit', 'send', 'print'],
  },
  {
    id: 'stm32-uart-receive',
    name: 'HAL_UART_Receive',
    category: 'uart',
    platform: 'stm32hal',
    description: '通过 UART 接收数据（阻塞）',
    signature: 'HAL_StatusTypeDef HAL_UART_Receive(UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t rx_buf[1];\nHAL_UART_Receive(&huart1, rx_buf, 1, 1000);`,
    keywords: ['接收', '输入', 'rx', 'receive', 'read'],
  },
  {
    id: 'stm32-uart-transmit-it',
    name: 'HAL_UART_Transmit_IT',
    category: 'uart',
    platform: 'stm32hal',
    description: '通过 UART 中断发送数据（非阻塞）',
    signature: 'HAL_StatusTypeDef HAL_UART_Transmit_IT(UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size)',
    snippet: `uint8_t tx_buf[] = "Hello\\r\\n";\nHAL_UART_Transmit_IT(&huart1, tx_buf, sizeof(tx_buf) - 1);`,
    keywords: ['中断', '非阻塞', 'it', 'async'],
  },
  // ── SPI ──
  {
    id: 'stm32-spi-init',
    name: 'HAL_SPI_Init',
    category: 'spi',
    platform: 'stm32hal',
    description: '初始化 SPI 外设',
    signature: 'HAL_StatusTypeDef HAL_SPI_Init(SPI_HandleTypeDef *hspi)',
    snippet: `SPI_HandleTypeDef hspi1 = {0};\nhspi1.Instance = SPI1;\nhspi1.Init.Mode = SPI_MODE_MASTER;\nhspi1.Init.Direction = SPI_DIRECTION_2LINES;\nhspi1.Init.DataSize = SPI_DATASIZE_8BIT;\nhspi1.Init.CLKPolarity = SPI_POLARITY_LOW;\nhspi1.Init.CLKPhase = SPI_PHASE_1EDGE;\nhspi1.Init.NSS = SPI_NSS_SOFT;\nhspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;\nHAL_SPI_Init(&hspi1);`,
    keywords: ['初始化', '主模式', 'master', 'cpol', 'cpha'],
  },
  {
    id: 'stm32-spi-transmit',
    name: 'HAL_SPI_Transmit',
    category: 'spi',
    platform: 'stm32hal',
    description: 'SPI 发送数据（阻塞）',
    signature: 'HAL_StatusTypeDef HAL_SPI_Transmit(SPI_HandleTypeDef *hspi, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t tx_data = 0x42;\nHAL_SPI_Transmit(&hspi1, &tx_data, 1, 100);`,
    keywords: ['发送', 'tx', 'transmit', 'send', 'mosi'],
  },
  {
    id: 'stm32-spi-receive',
    name: 'HAL_SPI_Receive',
    category: 'spi',
    platform: 'stm32hal',
    description: 'SPI 接收数据（阻塞）',
    signature: 'HAL_StatusTypeDef HAL_SPI_Receive(SPI_HandleTypeDef *hspi, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t rx_data;\nHAL_SPI_Receive(&hspi1, &rx_data, 1, 100);`,
    keywords: ['接收', 'rx', 'receive', 'miso'],
  },
  {
    id: 'stm32-spi-transmit-receive',
    name: 'HAL_SPI_TransmitReceive',
    category: 'spi',
    platform: 'stm32hal',
    description: 'SPI 全双工收发数据',
    signature: 'HAL_StatusTypeDef HAL_SPI_TransmitReceive(SPI_HandleTypeDef *hspi, uint8_t *pTxData, uint8_t *pRxData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t tx = 0x42, rx;\nHAL_SPI_TransmitReceive(&hspi1, &tx, &rx, 1, 100);`,
    keywords: ['全双工', '收发', 'full duplex', 'transfer'],
  },
  // ── Timer ──
  {
    id: 'stm32-tim-base-init',
    name: 'HAL_TIM_Base_Init',
    category: 'timer',
    platform: 'stm32hal',
    description: '初始化定时器基本功能',
    signature: 'HAL_StatusTypeDef HAL_TIM_Base_Init(TIM_HandleTypeDef *htim)',
    snippet: `TIM_HandleTypeDef htim2 = {0};\nhtim2.Instance = TIM2;\nhtim2.Init.Prescaler = 72 - 1;\nhtim2.Init.CounterMode = TIM_COUNTERMODE_UP;\nhtim2.Init.Period = 1000 - 1;\nhtim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;\nHAL_TIM_Base_Init(&htim2);`,
    keywords: ['初始化', '定时', 'prescaler', 'period', 'psc', 'arr'],
  },
  {
    id: 'stm32-tim-base-start',
    name: 'HAL_TIM_Base_Start',
    category: 'timer',
    platform: 'stm32hal',
    description: '启动定时器基本计数',
    signature: 'HAL_StatusTypeDef HAL_TIM_Base_Start(TIM_HandleTypeDef *htim)',
    snippet: `HAL_TIM_Base_Start(&htim2);`,
    keywords: ['启动', 'start', 'begin', 'run'],
  },
  {
    id: 'stm32-tim-pwm-start',
    name: 'HAL_TIM_PWM_Start',
    category: 'timer',
    platform: 'stm32hal',
    description: '启动 PWM 输出',
    signature: 'HAL_StatusTypeDef HAL_TIM_PWM_Start(TIM_HandleTypeDef *htim, uint32_t Channel)',
    snippet: `// 先配置 TIM 为 PWM 模式\nhtim2.Init.Prescaler = 72 - 1;\nhtim2.Init.Period = 1000 - 1;\nHAL_TIM_PWM_Init(&htim2);\n\nTIM_OC_InitTypeDef oc = {0};\noc.OCMode = TIM_OCMODE_PWM1;\noc.Pulse = 500;  // 占空比 50%\noc.OCPolarity = TIM_OCPOLARITY_HIGH;\nHAL_TIM_PWM_ConfigChannel(&htim2, &oc, TIM_CHANNEL_1);\nHAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1);`,
    keywords: ['pwm', '输出', '占空比', 'duty', 'waveform'],
  },
  {
    id: 'stm32-tim-interrupt',
    name: 'HAL_TIM_Base_Start_IT',
    category: 'timer',
    platform: 'stm32hal',
    description: '启动定时器中断',
    signature: 'HAL_StatusTypeDef HAL_TIM_Base_Start_IT(TIM_HandleTypeDef *htim)',
    snippet: `HAL_TIM_Base_Start_IT(&htim2);\n\n// 中断回调\nvoid HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {\n  if (htim->Instance == TIM2) {\n    HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);\n  }\n}`,
    keywords: ['中断', 'callback', 'irq', 'period elapsed'],
  },
  {
    id: 'stm32-tim-delay',
    name: 'HAL_Delay',
    category: 'timer',
    platform: 'stm32hal',
    description: '毫秒延时（基于 SysTick）',
    signature: 'void HAL_Delay(uint32_t Delay)',
    snippet: `HAL_Delay(500);  // 延时 500ms`,
    keywords: ['延时', 'delay', 'ms', '毫秒', 'wait'],
  },
  {
    id: 'stm32-tim-get-tick',
    name: 'HAL_GetTick',
    category: 'timer',
    platform: 'stm32hal',
    description: '获取系统启动以来的毫秒数',
    signature: 'uint32_t HAL_GetTick(void)',
    snippet: `uint32_t start = HAL_GetTick();\n// ... 执行操作 ...\nuint32_t elapsed = HAL_GetTick() - start;`,
    keywords: ['tick', '时间', 'time', 'ms', 'elapsed'],
  },
  // ── ADC ──
  {
    id: 'stm32-adc-init',
    name: 'HAL_ADC_Init',
    category: 'adc',
    platform: 'stm32hal',
    description: '初始化 ADC 外设',
    signature: 'HAL_StatusTypeDef HAL_ADC_Init(ADC_HandleTypeDef *hadc)',
    snippet: `ADC_HandleTypeDef hadc1 = {0};\nhadc1.Instance = ADC1;\nhadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;\nhadc1.Init.ScanConvMode = ADC_SCAN_DISABLE;\nhadc1.Init.ContinuousConvMode = DISABLE;\nhadc1.Init.NbrOfConversion = 1;\nhadc1.Init.SamplingTime = ADC_SAMPLETIME_71CYCLES_5;\nHAL_ADC_Init(&hadc1);`,
    keywords: ['初始化', '模数转换', 'analog', 'init'],
  },
  {
    id: 'stm32-adc-start',
    name: 'HAL_ADC_Start',
    category: 'adc',
    platform: 'stm32hal',
    description: '启动 ADC 转换',
    signature: 'HAL_StatusTypeDef HAL_ADC_Start(ADC_HandleTypeDef *hadc)',
    snippet: `HAL_ADC_Start(&hadc1);\nHAL_ADC_PollForConversion(&hadc1, 100);\nuint16_t value = HAL_ADC_GetValue(&hadc1);`,
    keywords: ['启动', 'start', 'conversion', '转换'],
  },
  {
    id: 'stm32-adc-poll',
    name: 'HAL_ADC_PollForConversion',
    category: 'adc',
    platform: 'stm32hal',
    description: '等待 ADC 转换完成',
    signature: 'HAL_StatusTypeDef HAL_ADC_PollForConversion(ADC_HandleTypeDef *hadc, uint32_t Timeout)',
    snippet: `HAL_ADC_PollForConversion(&hadc1, 100);\nuint16_t raw = HAL_ADC_GetValue(&hadc1);\nfloat voltage = raw * 3.3f / 4096.0f;`,
    keywords: ['轮询', '等待', 'poll', 'wait', 'blocking'],
  },
  {
    id: 'stm32-adc-get-value',
    name: 'HAL_ADC_GetValue',
    category: 'adc',
    platform: 'stm32hal',
    description: '读取 ADC 转换结果',
    signature: 'uint32_t HAL_ADC_GetValue(ADC_HandleTypeDef *hadc)',
    snippet: `uint32_t adc_val = HAL_ADC_GetValue(&hadc1);`,
    keywords: ['读取', '值', 'value', 'result', 'raw'],
  },
  // ── I2C ──
  {
    id: 'stm32-i2c-init',
    name: 'HAL_I2C_Init',
    category: 'i2c',
    platform: 'stm32hal',
    description: '初始化 I2C 外设',
    signature: 'HAL_StatusTypeDef HAL_I2C_Init(I2C_HandleTypeDef *hi2c)',
    snippet: `I2C_HandleTypeDef hi2c1 = {0};\nhi2c1.Instance = I2C1;\nhi2c1.Init.ClockSpeed = 100000;\nhi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;\nhi2c1.Init.OwnAddress1 = 0;\nhi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;\nHAL_I2C_Init(&hi2c1);`,
    keywords: ['初始化', 'init', 'scl', 'sda', 'clock'],
  },
  {
    id: 'stm32-i2c-master-transmit',
    name: 'HAL_I2C_Master_Transmit',
    category: 'i2c',
    platform: 'stm32hal',
    description: 'I2C 主机发送数据',
    signature: 'HAL_StatusTypeDef HAL_I2C_Master_Transmit(I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t data[] = {0x00, 0xFF};\nHAL_I2C_Master_Transmit(&hi2c1, 0x68 << 1, data, 2, 100);`,
    keywords: ['发送', '主机', 'master', 'transmit', 'write'],
  },
  {
    id: 'stm32-i2c-master-receive',
    name: 'HAL_I2C_Master_Receive',
    category: 'i2c',
    platform: 'stm32hal',
    description: 'I2C 主机接收数据',
    signature: 'HAL_StatusTypeDef HAL_I2C_Master_Receive(I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t buf[6];\nHAL_I2C_Master_Receive(&hi2c1, 0x68 << 1, buf, 6, 100);`,
    keywords: ['接收', '主机', 'master', 'receive', 'read'],
  },
  {
    id: 'stm32-i2c-mem-write',
    name: 'HAL_I2C_Mem_Write',
    category: 'i2c',
    platform: 'stm32hal',
    description: 'I2C 写入设备内部寄存器',
    signature: 'HAL_StatusTypeDef HAL_I2C_Mem_Write(I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t val = 0x01;\nHAL_I2C_Mem_Write(&hi2c1, 0x68 << 1, 0x6B, I2C_MEMADD_SIZE_8BIT, &val, 1, 100);`,
    keywords: ['写寄存器', 'register', 'mem write'],
  },
  {
    id: 'stm32-i2c-mem-read',
    name: 'HAL_I2C_Mem_Read',
    category: 'i2c',
    platform: 'stm32hal',
    description: 'I2C 读取设备内部寄存器',
    signature: 'HAL_StatusTypeDef HAL_I2C_Mem_Read(I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t *pData, uint16_t Size, uint32_t Timeout)',
    snippet: `uint8_t who_am_i;\nHAL_I2C_Mem_Read(&hi2c1, 0x68 << 1, 0x75, I2C_MEMADD_SIZE_8BIT, &who_am_i, 1, 100);`,
    keywords: ['读寄存器', 'register', 'mem read'],
  },
];
